In [7]:
import pandas as pd
import numpy as np
import seaborn as sns

In [8]:
k=[4,2.56789,9,87.9999,40,'hyderabad']
k

[4, 2.56789, 9, 87.9999, 40, 'hyderabad']

In [9]:
pd.Series(k)

0            4
1      2.56789
2            9
3      87.9999
4           40
5    hyderabad
dtype: object

In [10]:
a=np.random.randint(20,50,(5,4))
a

array([[30, 33, 28, 21],
       [21, 33, 34, 37],
       [46, 24, 31, 20],
       [34, 34, 31, 24],
       [21, 26, 48, 48]])

In [15]:
a.ndim

2

In [17]:
b=np.random.randint(100,200,(6,5))
b

array([[141, 185, 197, 152, 146],
       [133, 166, 189, 152, 113],
       [135, 166, 170, 198, 123],
       [172, 112, 103, 104, 135],
       [104, 125, 194, 139, 139],
       [169, 152, 179, 114, 161]])

In [19]:
b.shape

(6, 5)

In [21]:
b

array([[141, 185, 197, 152, 146],
       [133, 166, 189, 152, 113],
       [135, 166, 170, 198, 123],
       [172, 112, 103, 104, 135],
       [104, 125, 194, 139, 139],
       [169, 152, 179, 114, 161]])

In [23]:
pd.DataFrame(b)

0    1    2    3    4
0  141  185  197  152  146
1  133  166  189  152  113
2  135  166  170  198  123
3  172  112  103  104  135
4  104  125  194  139  139
5  169  152  179  114  161

In [59]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'], index = [1,2,3,4,5,6,])
df

Roll  name  age  adds  country
1   141   185  197   152      146
2   133   166  189   152      113
3   135   166  170   198      123
4   172   112  103   104      135
5   104   125  194   139      139
6   169   152  179   114      161

In [37]:
df

Roll  name  age  adds  country
0   141   185  197   152      146
1   133   166  189   152      113
2   135   166  170   198      123
3   172   112  103   104      135
4   104   125  194   139      139
5   169   152  179   114      161

In [43]:
df.iloc[0,0]

141

In [47]:
df.loc[0,['Roll','name','age']]

Roll    141
name    185
age     197
Name: 0, dtype: int32

In [49]:
df.iloc[0,0:3]

Roll    141
name    185
age     197
Name: 0, dtype: int32

In [51]:
df.iloc[0,[0,1,2]]

Roll    141
name    185
age     197
Name: 0, dtype: int32

In [55]:
df.iloc[[0,5]]

Roll  name  age  adds  country
0   141   185  197   152      146
5   169   152  179   114      161

In [57]:
df.iloc[[1,3,4]]

Roll  name  age  adds  country
1   133   166  189   152      113
3   172   112  103   104      135
4   104   125  194   139      139

In [61]:
df.loc[[1,2,3],['adds','name','age']]

adds  name  age
1   152   185  197
2   152   166  189
3   198   166  170

In [63]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
sns.load_dataset('yashwanth')